---
AWSTemplateFormatVersion: "2010-09-09"
Description: Enderscraft Public VPC Stack
Metadata:
  License: CC BY-NC 4.0
  Author: Josh Enders <josh.enders@gmail.com>

Parameters:
  ParameterVPCCIDRBlock:
    Description: "VPC CIDR Block"
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: "10.0.0.0/24"

  ParameterSubnetPublicCIDR:
    Description: "Public Subnet CIDR Block"
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: "10.0.0.0/26"

  ParameterMinecraftPort:
    Description: "Minecraft port"
    Type: String
    AllowedPattern: '\d{1,5}'
    Default: "25565"

  ParameterRCONPort:
    Description: "RCON port"
    Type: String
    AllowedPattern: '\d{1,5}'
    Default: "25575"

  ParameterHostedZone:
    Description: "Domain Name"
    Type: String

  ParameterIAMUser:
    Description: "IAM User"
    Type: String
    Default: "enderscraft"

  ParameterLogRetentionDays:
    Description: "Days of log retention for tasks and services"
    Type: String
    AllowedPattern: '^(1|3|5|7|14|30|60|90|120|150|180|365|400|545|731|1827|3653)$'
    Default: "7"

Resources:
  # DNS
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name:
        Ref: ParameterHostedZone

  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref ParameterVPCCIDRBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-VPC

  # Network Gateways
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Network ACLs
  NetworkAclDefault:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-NetworkAclDefault

  # Public Subnet
  SubnetPublic:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref ParameterSubnetPublicCIDR
      AvailabilityZone: !Select [0, !GetAZs ]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-SubnetPublic

  RouteTableSubnetPublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-RouteTableSubnetPublic

  RouteSubnetPublicDefault:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTableSubnetPublic
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociationSubnetPublic:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPublic
      RouteTableId: !Ref RouteTableSubnetPublic

  # Security Groups
  SecurityGroupFargateTasks:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Security Group for Fargate Tasks
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: !Sub "Allow traffic on port ${ParameterMinecraftPort}"
          FromPort: !Ref ParameterMinecraftPort
          IpProtocol: tcp
          ToPort: !Ref ParameterMinecraftPort

        - CidrIp: 0.0.0.0/0
          Description: !Sub "Allow traffic on port ${ParameterRCONPort}"
          FromPort: !Ref ParameterRCONPort
          IpProtocol: tcp
          ToPort: !Ref ParameterRCONPort
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-SecurityGroupFargateTasks

  # IAM
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref ParameterIAMUser

  IAMRoleECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: "Role for execution ECS Tasks"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      RoleName: ecsTaskExecutionRole
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-IAMRoleECSTaskExecutionRole

  IAMPolicyFargateCLI:
    Type: 'AWS::IAM::Policy'
    DependsOn: IAMUser
    Properties:
      PolicyName: FargateCLIPolicy
      Users: 
        - !Ref ParameterIAMUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "acm:ListCertificates"
              - "ec2:DescribeNetworkInterfaces"
              - "ecs:CreateCluster"
              - "ecs:DescribeTaskDefinition"
              - "ecs:ListServices"
              - "ecs:ListTasks"
              - "ecs:RegisterTaskDefinition"
              - "elasticloadbalancing:DescribeLoadBalancers"
            Resource: '*'

          - Effect: Allow
            Action:
              - "ecs:RunTask"
            Resource: !Sub "arn:aws:ecs:*:${AWS::AccountId}:task-definition/*:*"

          - Effect: Allow
            Action:
              - "ecs:DescribeTasks"
              - "ecs:StopTask"
              - "iam:GetRole"
              - "iam:PassRole"
              - "logs:CreateLogGroup"
              - "logs:FilterLogEvents"
            Resource:
              - !Sub "arn:aws:ecs:*:${AWS::AccountId}:task/fargate/*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole"
              - !Sub "arn:aws:logs:*:${AWS::AccountId}:log-group:/fargate/*/*:*:"

          - Effect: Allow
            Action:
              - "ecs:CreateService"
              - "ecs:DeleteService"
              - "ecs:DescribeServices"
              - "ecs:UpdateService"
              - "sts:AssumeRole"
            Resource:
              - !Sub "arn:aws:ecs:*:${AWS::AccountId}:service/fargate/*"
              - !Sub "arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole"

  # ECR
  ECRRepository:
    Type: AWS::ECR::Repository
    DependsOn: IAMRoleECSTaskExecutionRole
    Properties:
      RepositoryName: !Sub ${AWS::StackName}
      ImageScanningConfiguration:
        scanOnPush: true
      ImageTagMutability: "MUTABLE"
      LifecyclePolicy:
        LifecyclePolicyText: |-
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only one untagged image, expire all others",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "imageCountMoreThan",
                  "countNumber": 1
                },
                "action": {
                  "type": "expire"
                  }
                }
            ]
          }
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole"
            Action:
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:BatchGetImage"
              - "ecr:DescribeImages"
              - "ecr:DescribeRepositories"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:ListImages"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ECRRepository

  LogGroupFargateTask:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/fargate/task/${AWS::StackName}"
      RetentionInDays: !Ref ParameterLogRetentionDays

  LogGroupFargateService:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/fargate/service/${AWS::StackName}"
      RetentionInDays: !Ref ParameterLogRetentionDays

Outputs:
  ns1:
    Value: !Select [0, !GetAtt HostedZone.NameServers]
  ns2:
    Value: !Select [1, !GetAtt HostedZone.NameServers]
  ns3:
    Value: !Select [2, !GetAtt HostedZone.NameServers]
  ns4:
    Value: !Select [3, !GetAtt HostedZone.NameServers]